apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  datasource-url: c3ByaW5nZGV2ZWxvcG1lbnQtY2FzZQ==  # Base64 encoded database URL
  datasource-username: YWRtaW4=  # Base64 encoded username
  datasource-password: cGFzc3dvcmQ=  # Base64 encoded password
